### ISSUE TITLE
error making: python-pytorch-rocm 1.7.1-7

### ISSUE THREAD

**Issue by chiboreache** [rocm-arch/python-pytorch-rocm#23]
archlinux
yay

```bash
[1392/4811] Running gen_proto.py on onnx/onnx.in.proto
Processing /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/third_party/onnx/onnx/onnx.in.proto
Writing /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx/onnx/onnx_onnx_torch-ml.proto
Writing /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx/onnx/onnx_onnx_torch-ml.proto3
Writing /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx/onnx/onnx-ml.pb.h
generating /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx/onnx/onnx_pb.py
[1395/4811] Running C++ protocol buffer compiler on /home/chibo/.cac...-1.7.1-opt-rocm/build/third_party/onnx/onnx/onnx_onnx_torch-ml.proto
FAILED: third_party/onnx/onnx/onnx_onnx_torch-ml.pb.cc third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h 
cd /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx && /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/bin/protoc-3.11.4.0 /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx/onnx/onnx_onnx_torch-ml.proto -I /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx --cpp_out dllexport_decl=ONNX_API:/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx && /usr/bin/cmake -DFILENAME=/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h -DNAMESPACES=onnx_torch -P /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/cmake/ProtoBufPatch.cmake && /usr/bin/cmake -DFILENAME=/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/build/third_party/onnx/onnx/onnx_onnx_torch-ml.pb.cc -DNAMESPACES=onnx_torch -P /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/cmake/ProtoBufPatch.cmake
[1402/4811] Building CXX object third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8Depthwise3DAvx2.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/setup.py", line 760, in <module>
    build_deps()
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/setup.py", line 310, in build_deps
    build_caffe2(version=version,
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-opt-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...
error making: python-pytorch-rocm
```

**Comment by chiboreache** [comment]
!! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by chiboreache** [comment]
having trouble during build with python-torchvision-git python-detectron2-cuda

**Comment by chiboreache** [comment]
get new pc, but still having the issue

`ytorch-1.7.1-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)`

and guess what?

`Installing caffe2-cuda will remove: python-pytorch-cuda (python-pytorch)`

all this makes me completely lost..

**Comment by chiboreache** [comment]
```sh
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;NDEBUG;ONNX_ML=1;ONNXIFI_ENABLE_EXT=1;ONNX_NAMESPACE=onnx_torch;IDEEP_USE_MKL;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1;USE_EXTERNAL_MZCRC;MINIZ_DISABLE_ZIP_READER_CRC32_CHECKS
--   CMAKE_PREFIX_PATH     : /usr/lib/python3.9/site-packages
--   CMAKE_INSTALL_PREFIX  : /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/torch
-- 
--   TORCH_VERSION         : 1.7.0
--   CAFFE2_VERSION        : 1.7.0
--   BUILD_CAFFE2          : ON
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_CAFFE2_MOBILE   : OFF
--   BUILD_STATIC_RUNTIME_BENCHMARK: OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 3.9.1
--     Python executable   : /usr/bin/python
--     Pythonlibs version  : 3.9.1
--     Python library      : /usr/lib/libpython3.9.so.1.0
--     Python includes     : /usr/include/python3.9
--     Python site-packages: lib/python3.9/site-packages
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   BUILD_JNI             : OFF
--   BUILD_MOBILE_AUTOGRAD : OFF
--   INTERN_BUILD_MOBILE   : 
--   USE_ASAN              : OFF
--   USE_CPP_CODE_COVERAGE : OFF
--   USE_CUDA              : OFF
--   USE_ROCM              : ON
--   USE_EIGEN_FOR_BLAS    : 
--   USE_FBGEMM            : ON
--     USE_FAKELOWP          : OFF
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_MKLDNN_CBLAS      : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : ON
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : ON
--   USE_TBB               : OFF
--   USE_VULKAN            : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : ON
--   USE_PYTORCH_QNNPACK   : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : ON
--     USE_GLOO            : ON
--     USE_TENSORPIPE      : ON
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : pthreadpool;cpuinfo;qnnpack;pytorch_qnnpack;nnpack;XNNPACK;fbgemm;/usr/lib/libnuma.so;fp16;/usr/lib/openmpi/libmpi_cxx.so;/usr/lib/openmpi/libmpi.so;gloo;tensorpipe;aten_op_header_gen;foxi_loader;rt;fmt::fmt-header-only;gcc_s;gcc;dl
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build
Finished running cmake. Run "ccmake build" or "cmake-gui build" to adjust build options and "python setup.py install" to build.
Building wheel torch-1.7.0a0
-- Building version 1.7.0a0
cmake --build . --target install --config Release -- -j 32
ninja: error: '/opt/rocm/hip/lib/libamdhip64.so4a3c144', needed by 'caffe2/python/caffe2_pybind11_state_hip.cpython-39-x86_64-linux-gnu.so', missing and no known rule to make it
Traceback (most recent call last):
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/setup.py", line 760, in <module>
    build_deps()
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/setup.py", line 310, in build_deps
    build_caffe2(version=version,
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 349, in build
    self.run(build_args, my_env)
  File "/home/chibo/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '32']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...
error making: python-pytorch-rocm
↪ 
```

**Comment by acxz** [comment]
@chiboreache I'm going to close this issue as this could very well be an outdated issue with new versions of rocm and pytorch. I'm currently rewriting the PKGBUILD to use the newer rocm packages and I'll let you know when that is ready.
