### ISSUE TITLE
Error on build: FAILED: caffe2/contrib/aten/aten_op.h 

### ISSUE THREAD

**Issue by Stefan2409** [rocm-arch/python-pytorch-rocm#24]
I'm getting the following error by building python-pytorch-opt-rocm:

[2581/4780] Generating contrib/aten/aten_op.h
FAILED: caffe2/contrib/aten/aten_op.h 
cd /home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2 && /usr/bin/python /home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/caffe2/contrib/aten/gen_op.py --aten_root=/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/caffe2/../aten --template_dir=/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/caffe2/contrib/aten --yaml_dir=/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/../aten/src/ATen --install_dir=/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/contrib/aten
Traceback (most recent call last):
  File "/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/caffe2/contrib/aten/gen_op.py", line 40, in <module>
    from tools.codegen.code_template import CodeTemplate as CT
ModuleNotFoundError: No module named 'tools.codegen'
[2583/4780] Generating ../../../torch/_C/__init__.pyi, ../../../torch/_C/_VariableFunctions.pyi, ../../../torch/nn/functional.pyi
Writing ./torch/_C/__init__.pyi
Writing ./torch/_C/_VariableFunctions.pyi
Writing ./torch/_VF.pyi
Writing ./torch/nn/functional.pyi
Writing ./torch/_C/_nn.pyi
[2585/4780] Generating ../../torch/csrc/autograd/generated/Functions.cpp, ../../torch/csrc/jit/generated/generated_unboxing_wrappers_0....alg_functions.cpp, ../../torch/csrc/autograd/generated/python_functions.h, ../../torch/testing/_internal/generated/annotated_fn_args.py
Writing torch/csrc/autograd/generated/python_functions.h
Writing torch/csrc/autograd/generated/python_functions.cpp
Writing torch/csrc/autograd/generated/python_variable_methods.cpp
Writing torch/csrc/autograd/generated/python_torch_functions.cpp
Writing torch/csrc/autograd/generated/python_nn_functions.cpp
Writing torch/csrc/autograd/generated/python_fft_functions.cpp
Writing torch/csrc/autograd/generated/python_linalg_functions.cpp
Writing torch/csrc/autograd/generated/VariableType.h
Writing torch/csrc/autograd/generated/VariableType_0.cpp
Writing torch/csrc/autograd/generated/TraceType_0.cpp
Writing torch/csrc/autograd/generated/VariableType_1.cpp
Writing torch/csrc/autograd/generated/TraceType_1.cpp
Writing torch/csrc/autograd/generated/VariableType_2.cpp
Writing torch/csrc/autograd/generated/TraceType_2.cpp
Writing torch/csrc/autograd/generated/VariableType_3.cpp
Writing torch/csrc/autograd/generated/TraceType_3.cpp
Writing torch/csrc/autograd/generated/VariableType_4.cpp
Writing torch/csrc/autograd/generated/TraceType_4.cpp
Writing torch/csrc/autograd/generated/VariableTypeEverything.cpp
Writing torch/csrc/autograd/generated/TraceTypeEverything.cpp
Writing torch/csrc/autograd/generated/RegistrationDeclarations.h
Writing torch/csrc/autograd/generated/Functions.h
Writing torch/csrc/autograd/generated/Functions.cpp
Writing torch/csrc/autograd/generated/variable_factories.h
Writing torch/csrc/jit/generated/generated_unboxing_wrappers_0.cpp
Writing torch/csrc/jit/generated/generated_unboxing_wrappers_1.cpp
Writing torch/csrc/jit/generated/generated_unboxing_wrappers_2.cpp
Writing torch/testing/_internal/generated/annotated_fn_args.py
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/setup.py", line 760, in <module>
    build_deps()
  File "/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/setup.py", line 310, in build_deps
    build_caffe2(version=version,
  File "/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 349, in build
    self.run(build_args, my_env)
  File "/home/stefan/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 1.
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
error making: python-pytorch-rocm (python-pytorch-opt-rocm)

This is a known issue in regard to the pytorch github repository:
https://github.com/pytorch/pytorch/issues/47553

Should be fixed soon...

**Comment by acxz** [comment]
Seems like this issue has been fixed in the newer pytorch versions. As such closing this issue.
